# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            set -e
            git config --global --add safe.directory /srv/llm-chatbot
            cd /srv/llm-chatbot

            # Pull the latest code
            git pull origin main

            # Build the React frontend
            cd saas-frontend
            rm -rf build
            npm install
            npm run build

            # Restart backend and reload Nginx
            cd ../saas-backend
            sudo systemctl daemon-reload
            sudo systemctl restart llmchatbot.service
            sudo systemctl reload nginx
