# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd /srv/llm-chatbot
            git pull origin main
            cd saas-frontend
            rm -rf build
            npm install
            npm run build
            cd ../saas-backend
            sudo systemctl daemon-reload
            sudo systemctl restart llmchatbot.service
